### ISSUE TITLE
own live track is seen as a "friend"

### ISSUE THREAD

**Issue by vlootje** [skylines-project/skylines#1657]
My live track (which I create with Skylines Tracker and a correct live tracking key) is seen as a track of a "friend". Yet it is under my own name, I can open it, but I cannot store it or download it. So next day, with new live tracks, it is lost. 
What to do?

**Comment by Turbo87** [comment]
> I cannot store it or download it
> What to do?

the live tracking data is not meant to be downloaded as it's "live" and due to reception issue can have significant gaps in the track. if you want a recording of your flight you should use an IGC flight recorder or an app which does the same thing.

 I don't know what "Skylines Tracker" is. The only "official" Skylines live tracking client is XCSoar.

**Comment by vlootje** [comment]
Tobias, thanks for your swift response! I get the picture.
The tracker I used is
https://play.google.com/store/apps/details?id=ch.luethi.skylinestracker
