### ISSUE TITLE
Email notifications

### ISSUE THREAD

**Issue by roeles** [skylines-project/skylines#222]
Instead of requiring people to log in to see if there are notifications, why not drop them an email (if they indicate they would like that)?

**Comment by Turbo87** [comment]
to cut down on the number of open issues on this project we are introducing a feature request queue: https://github.com/skylines-project/skylines/issues?q=label%3Afeature-request+is%3Aclosed+sort%3Areactions-%2B1+. we will close feature requests immediately and label them with "feature-request" so that they will show up in the queue, which is sorted by 👍 reactions. since this issue is also a feature request we have labeled it appropriately and will close it now.
