### ISSUE TITLE
Support for NMEA logs

### ISSUE THREAD

**Issue by roeles** [skylines-project/skylines#223]
Given that a pilot wants to enter all flight info normally provided by IGC files, it makes sense to support NMEA logs as well.

**Comment by pyrog** [comment]
You could use the [online version](http://www.gpsvisualizer.com/gpsbabel/) of [GPSbabel](https://www.gpsbabel.org) to convert your data.

Field | value
--- | ---
Type of GPS data you want to convert: | Tracks [T]
Input file format: | NMEA 0183 sentences [W][T]
Output file format: | FAI/IGC Flight Recorder Data Format [T][R]

**Comment by Turbo87** [comment]
to cut down on the number of open issues on this project we are introducing a feature request queue: https://github.com/skylines-project/skylines/issues?q=label%3Afeature-request+is%3Aclosed+sort%3Areactions-%2B1+. we will close feature requests immediately and label them with "feature-request" so that they will show up in the queue, which is sorted by 👍 reactions. since this issue is also a feature request we have labeled it appropriately and will close it now.
