### ISSUE TITLE
Enabling Realtime Tracking for use in SAR Operations

### ISSUE THREAD

**Issue by Exadios** [skylines-project/skylines#250]
I would like to see the Real Time Tracking function to be made useful for Search and Rescue operations. This would require the ability to be able to read a geodetic position of the aircraft from the trace - especially the final positions.

**Comment by Turbo87** [comment]
to cut down on the number of open issues on this project we are introducing a feature request queue: https://github.com/skylines-project/skylines/issues?q=label%3Afeature-request+is%3Aclosed+sort%3Areactions-%2B1+. we will close feature requests immediately and label them with "feature-request" so that they will show up in the queue, which is sorted by 👍 reactions. since this issue is also a feature request we have labeled it appropriately and will close it now.
