### ISSUE TITLE
Show flight phase information in fullscreen map view

### ISSUE THREAD

**Issue by TobiasLohner** [skylines-project/skylines#258]
The fullscreen map has some space left in the info column to show some information about the phase the glider is in (cruise, circling). We should utilize that space to show the average glide ratio/average climb rate and distance (horizontal/vertical) of the current phase.

**Comment by Turbo87** [comment]
to cut down on the number of open issues on this project we are introducing a feature request queue: https://github.com/skylines-project/skylines/issues?q=label%3Afeature-request+is%3Aclosed+sort%3Areactions-%2B1+. we will close feature requests immediately and label them with "feature-request" so that they will show up in the queue, which is sorted by 👍 reactions. since this issue is also a feature request we have labeled it appropriately and will close it now.
