### ISSUE TITLE
not showing date

### ISSUE THREAD

**Issue by lucaspirola** [skylines-project/skylines#267]
when uploading multiple IGC files, the page should display the date of the flight, so the user don't need to decode it by igc file.  it will make easier to import a lot of flights at once.

**Comment by Turbo87** [comment]
to cut down on the number of open issues on this project we are introducing a feature request queue: https://github.com/skylines-project/skylines/issues?q=label%3Afeature-request+is%3Aclosed+sort%3Areactions-%2B1+. we will close feature requests immediately and label them with "feature-request" so that they will show up in the queue, which is sorted by 👍 reactions. since this issue is also a feature request we have labeled it appropriately and will close it now.
