### ISSUE TITLE
Transition to previous flight list after deleting flight

### ISSUE THREAD

**Issue by lucaspirola** [skylines-project/skylines#268]
after delete of a flight, the site opens flights of the day.  It's natural that it should go to the page where the button SHOW was for the now deleted flight (for example, flightbook)

**Comment by Turbo87** [comment]
to cut down on the number of open issues on this project we are introducing a feature request queue: https://github.com/skylines-project/skylines/issues?q=label%3Afeature-request+is%3Aclosed+sort%3Areactions-%2B1+. we will close feature requests immediately and label them with "feature-request" so that they will show up in the queue, which is sorted by 👍 reactions. since this issue is also a feature request we have labeled it appropriately and will close it now.
