### ISSUE TITLE
Provide regular (monthly?) data dumps

### ISSUE THREAD

**Issue by bbonamin** [skylines-project/skylines#276]
Since Skylines is an Open Data project, and (I think) we don't claim to own the data that users provide to us, it could be very interesting to follow [the example of the Stack Exchange network by providing our own regular data dumps](http://blog.stackoverflow.com/2009/06/stack-overflow-creative-commons-data-dump/).

Stack Exchange used to provide a monthly data dump via bitorrent, which is a very inexpensive process and allows the data to be replicated anywhere.

Data dumps could be useful for people or organizations doing mass analysis of IGC files, without killing the skylines production server.

Thoughts?

**Comment by Turbo87** [comment]
to cut down on the number of open issues on this project we are introducing a feature request queue: https://github.com/skylines-project/skylines/issues?q=label%3Afeature-request+is%3Aclosed+sort%3Areactions-%2B1+. we will close feature requests immediately and label them with "feature-request" so that they will show up in the queue, which is sorted by 👍 reactions. since this issue is also a feature request we have labeled it appropriately and will close it now.
