### ISSUE TITLE
Feature request: Wind analysis

### ISSUE THREAD

**Issue by roeles** [skylines-project/skylines#282]
Using one of the several wind-detection algorithms, it might be interesting to detect the wind during a flight.

Should the XCSoar tool AnalyseFlight not be suitable enoug, given the usual inter-fix time in IGC files, I think Tobias (or I) might have a suitable algorithm to estimate the wind pretty well.

**Comment by Turbo87** [comment]
to cut down on the number of open issues on this project we are introducing a feature request queue: https://github.com/skylines-project/skylines/issues?q=label%3Afeature-request+is%3Aclosed+sort%3Areactions-%2B1+. we will close feature requests immediately and label them with "feature-request" so that they will show up in the queue, which is sorted by 👍 reactions. since this issue is also a feature request we have labeled it appropriately and will close it now.
