### ISSUE TITLE
Analysis for custom time range 

### ISSUE THREAD

**Issue by fb** [skylines-project/skylines#293]
For cycling I'm using [Strava](http://www.strava.com) (freemium, non-free, :-1:).

There is a nice feature for analysis. You can click-drag any range from the "barogram" and get statistics for that time range (avg. speed, time, distance, …). I attached a screenshot illustrating this feature.

![strava-custom-range](https://cloud.githubusercontent.com/assets/51237/2625009/160d32d4-bd74-11e3-85d8-d54bb29dd7bc.png)

I would like to have something like this in skylines. After selecting a range we could run analysis on that particular part of the flight and get distance between beginning and end, avg. speed, GR, etc.

What do you think?

**Comment by Turbo87** [comment]
to cut down on the number of open issues on this project we are introducing a feature request queue: https://github.com/skylines-project/skylines/issues?q=label%3Afeature-request+is%3Aclosed+sort%3Areactions-%2B1+. we will close feature requests immediately and label them with "feature-request" so that they will show up in the queue, which is sorted by 👍 reactions. since this issue is also a feature request we have labeled it appropriately and will close it now.
