### ISSUE TITLE
Please add the "Apollo Fox" UL flight name to the available flights

### ISSUE THREAD

**Issue by szuniverse** [skylines-project/skylines#305]
Hi. It would be nice if you add the "Apollo Fox" UL light to the flights list. Thanks!
Here is the flight: http://www.tampabayaerosport.com/images/WhiteApolloFox.jpg

**Comment by pyrog** [comment]
> Here is the flight: http://www.tampabayaerosport.com/images/WhiteApolloFox.jpg

This link is dead.

But did you mean: Add [Apollo Fox](https://en.wikipedia.org/wiki/Apollo_Fox) to the **aircraft type** list in the [Upload Flight](https://skylines.aero/flights/upload) ?
If yes, see #545

**Comment by Turbo87** [comment]
to cut down on the number of open issues on this project we are introducing a feature request queue: https://github.com/skylines-project/skylines/issues?q=label%3Afeature-request+is%3Aclosed+sort%3Areactions-%2B1+. we will close feature requests immediately and label them with "feature-request" so that they will show up in the queue, which is sorted by 👍 reactions. since this issue is also a feature request we have labeled it appropriately and will close it now.
