### ISSUE TITLE
Average bank angle while circling

### ISSUE THREAD

**Issue by Adrien81** [skylines-project/skylines#306]
Hi,
Should you find interesting to display the average bank angle during a circling phase (permanently or when hovering the line with mouse), then the formula is:
sin ( phi ) = 2 . PI . N . GS / (T . g)
where
phi : average bank
PI : 3,141...
N : number or turns
GS : average ground speed (m/s)
T : duration of the thermal (s)
g : 9,81 m/s2

**Comment by Turbo87** [comment]
to cut down on the number of open issues on this project we are introducing a feature request queue: https://github.com/skylines-project/skylines/issues?q=label%3Afeature-request+is%3Aclosed+sort%3Areactions-%2B1+. we will close feature requests immediately and label them with "feature-request" so that they will show up in the queue, which is sorted by 👍 reactions. since this issue is also a feature request we have labeled it appropriately and will close it now.
