### ISSUE TITLE
Widget - Verbesserungsvorschläge

### ISSUE THREAD

**Issue by elchupete** [skylines-project/skylines#308]
Alle links (Pilot, Flugplatz, Details) öffnen die Skylines Seite im selben Fenster. Es wäre klasse, wenn ihr es so ändern könntet, dass die Seite in einem neuen Fenster geöffnet wird, so dass der Besucher auf unserer Vereinsseite bleibt.

**Comment by Turbo87** [comment]
to cut down on the number of open issues on this project we are introducing a feature request queue: https://github.com/skylines-project/skylines/issues?q=label%3Afeature-request+is%3Aclosed+sort%3Areactions-%2B1+. we will close feature requests immediately and label them with "feature-request" so that they will show up in the queue, which is sorted by 👍 reactions. since this issue is also a feature request we have labeled it appropriately and will close it now.
