### ISSUE TITLE
Widget - Languages

### ISSUE THREAD

**Issue by elchupete** [skylines-project/skylines#309]
Mit Safari scheint es das Problem zu geben, dass die Sprache nicht erkannt wird.

Unter www.hvl-boberg.de habe ich das Widget eingebunden. Im Firefox (Chrome, Opera) auf Mac OSX wird alles in Deutsch angezeigt. Nur Safari meint hier die Englishen Texte / Datumsformate anzeigen zu müssen.

**Comment by pyrog** [comment]
Do you have always this issue.
I don't have it on macOS Sierra and Safari Version 10.0.1 (12602.2.14.0.7)

**Comment by Turbo87** [comment]
he will definitely always have this issue as I've removed the translation code from the widget code

**Comment by pyrog** [comment]
Sorry, I probably didn't understood his problem (Google automatic translation 😉 )

**Comment by Turbo87** [comment]
to cut down on the number of open issues on this project we are introducing a feature request queue: https://github.com/skylines-project/skylines/issues?q=label%3Afeature-request+is%3Aclosed+sort%3Areactions-%2B1+. we will close feature requests immediately and label them with "feature-request" so that they will show up in the queue, which is sorted by 👍 reactions. since this issue is also a feature request we have labeled it appropriately and will close it now.
