### ISSUE TITLE
Task declaration / retrieval

### ISSUE THREAD

**Issue by staylo** [skylines-project/skylines#353]
The ability to declare a task to, and retrieve a task from skylines via an API ( ref #226 ) would have multiple uses:

Adds task to live tracking page for context.

Planning: When planning your flight, look at the tasks other users from neighbouring airfields are declaring and compare with your own expectations.

Task sharing: Client application filters tasks from Skylines with the same starting location, user then picks the desired task. This becomes the active task in the client application.

Ad-hoc team flying (with FLARM): After downloading the Skylines list of declared tasks to the client application, aircraft flying the same task, or a task that shares a leg with the user's task.

**Comment by Turbo87** [comment]
to cut down on the number of open issues on this project we are introducing a feature request queue: https://github.com/skylines-project/skylines/issues?q=label%3Afeature-request+is%3Aclosed+sort%3Areactions-%2B1+. we will close feature requests immediately and label them with "feature-request" so that they will show up in the queue, which is sorted by 👍 reactions. since this issue is also a feature request we have labeled it appropriately and will close it now.
