### ISSUE TITLE
Skylines should detect "virtual" flights

### ISSUE THREAD

**Issue by scls19fr** [skylines-project/skylines#396]
Hello,

I've just upload a Condor Soaring flight to Skylines.
I think it will be fair to ever auto detect these kind of virtual flights or to provide to user a button to explain that this flight is virtual.

Condor Soaring original IGC can have future date. So I changed date from 21/06/2015 to 21/06/2014 to allow this file to be uploaded.

Kind regards

**Comment by Turbo87** [comment]
:+1:

**Comment by Turbo87** [comment]
to cut down on the number of open issues on this project we are introducing a feature request queue: https://github.com/skylines-project/skylines/issues?q=label%3Afeature-request+is%3Aclosed+sort%3Areactions-%2B1+. we will close feature requests immediately and label them with "feature-request" so that they will show up in the queue, which is sorted by 👍 reactions. since this issue is also a feature request we have labeled it appropriately and will close it now.
