### ISSUE TITLE
C records in IGC files are not taken into account

### ISSUE THREAD

**Issue by scls19fr** [skylines-project/skylines#397]
Hello,

I've upload this (virtual) flight https://skylines.aero/flights/46389/
but it seems that C records (task declaration) are not taken into account.

Kind regards

**Comment by Turbo87** [comment]
that is correct. how should it be taken into account?

**Comment by scls19fr** [comment]
In fact we should see something like
![capture d ecran 2015-05-11 a 17 20 34](https://cloud.githubusercontent.com/assets/109167/7568308/4921a91a-f802-11e4-8bba-a30e09a77cfb.png)

**Comment by scls19fr** [comment]
I also think that we should be able to display easily other pilots flights for same task declaration (C records in IGC file)

**Comment by scls19fr** [comment]
You can get some IGC files for testing here http://www.condor-club.eu/ftrrank/0/?fpl=885c048e53bc9d0795d807f513a574a7

**Comment by pyrog** [comment]
- [skylines/tests/data/simple.igc](https://github.com/skylines-project/skylines/blob/master/tests/data/simple.igc)
- https://skylines.aero/files/6bgv7n51.igc

[C Record format.pdf](https://github.com/skylines-project/skylines/files/597006/C.Record.format.pdf)
Source: http://www.fai.org/gnss-recording-devices/igc-approved-flight-recorders

@Turbo87 PS: You could find several file on Skylines server
`grep "^C" /vagrant/htdocs/files/*`

**Comment by Turbo87** [comment]
to cut down on the number of open issues on this project we are introducing a feature request queue: https://github.com/skylines-project/skylines/issues?q=label%3Afeature-request+is%3Aclosed+sort%3Areactions-%2B1+. we will close feature requests immediately and label them with "feature-request" so that they will show up in the queue, which is sorted by 👍 reactions. since this issue is also a feature request we have labeled it appropriately and will close it now.
