### ISSUE TITLE
Add color to track

### ISSUE THREAD

**Issue by scls19fr** [skylines-project/skylines#398]
Hello,

it will be nice to provide a color mode for track
- solid color
- colored by climb (m/s)
- colored by altitude (m)
- colored by ground speed (km/h)
- colored by climb (with energy compensation (m/s)
  
  see https://en.wikipedia.org/wiki/Variometer#Total_energy_compensation_in_theory
- colored by time

see https://github.com/twpayne/igc2kmz/

Kind regards

**Comment by scls19fr** [comment]
Some screenshots

Colored by climb
![climb](https://cloud.githubusercontent.com/assets/109167/7568947/f8a703fa-f805-11e4-9522-0393fd0bd6dd.png)

Colored by ground speed
![groundspeed](https://cloud.githubusercontent.com/assets/109167/7568948/f8ab096e-f805-11e4-82b8-55ef2c9212da.png)

Colored by altitude
![altitude](https://cloud.githubusercontent.com/assets/109167/7568946/f8a3465c-f805-11e4-92f5-8b25fbb266cc.png)

Colored by time
![time](https://cloud.githubusercontent.com/assets/109167/7568949/f8acdc4e-f805-11e4-88f2-dea35eb3bc1d.png)

I can't show colored by glimb with enery compensation because there is a little bug in igc2kmz.

**Comment by Turbo87** [comment]
to cut down on the number of open issues on this project we are introducing a feature request queue: https://github.com/skylines-project/skylines/issues?q=label%3Afeature-request+is%3Aclosed+sort%3Areactions-%2B1+. we will close feature requests immediately and label them with "feature-request" so that they will show up in the queue, which is sorted by 👍 reactions. since this issue is also a feature request we have labeled it appropriately and will close it now.
