### ISSUE TITLE
Live tracking of virtual flights

### ISSUE THREAD

**Issue by scls19fr** [skylines-project/skylines#399]
Hello,

it's possible to connect XCSoar to Condor Soaring
see ​https://www.youtube.com/watch?v=YfGrp_Eq78o

It could lead to confusion between virtual flights and real flights.

Skylines should receive a parameter from XCSoar to explain it is a virtual flight

See: http://bugs.xcsoar.org/ticket/3526 on XCsoar side

Kind regards

**Comment by Turbo87** [comment]
to cut down on the number of open issues on this project we are introducing a feature request queue: https://github.com/skylines-project/skylines/issues?q=label%3Afeature-request+is%3Aclosed+sort%3Areactions-%2B1+. we will close feature requests immediately and label them with "feature-request" so that they will show up in the queue, which is sorted by 👍 reactions. since this issue is also a feature request we have labeled it appropriately and will close it now.
