### ISSUE TITLE
Follow Club or Airport

### ISSUE THREAD

**Issue by lordfolken** [skylines-project/skylines#405]
Ability to follow a certain Club or even an Airport. Maybe not the live-tracking, but be informed of flights from that location.

**Comment by jharting** [comment]
+1 this would be helpful. Alternatively, it would be neat if on the "club members" page there was a follow/unfollow button right next to each club member. That way I could simply see if I am following all members of a given club and if not fix that with a few clicks without leaving the listing page.

**Comment by Turbo87** [comment]
to cut down on the number of open issues on this project we are introducing a feature request queue: https://github.com/skylines-project/skylines/issues?q=label%3Afeature-request+is%3Aclosed+sort%3Areactions-%2B1+. we will close feature requests immediately and label them with "feature-request" so that they will show up in the queue, which is sorted by 👍 reactions. since this issue is also a feature request we have labeled it appropriately and will close it now.
