### ISSUE TITLE
Co-pilots can only be chosen from your own club

### ISSUE THREAD

**Issue by Tataffe** [skylines-project/skylines#407]
I accompanied my brother on a flight yesterday: https://skylines.aero/flights/53156/

We both have a Skylines account, however, he could not choose me as his co-pilot upon uploading the flight since I am a member of a different club. Instead, he had to type in my name and now the flight does not show up in my profile.

The list of selectable pilots during flight upload should include at least followers and followed pilots. Also it would be nice to have a search function included to look for the other pilot, if you do not follow each other and do not fly in the same club.

Regards

**Comment by Turbo87** [comment]
to cut down on the number of open issues on this project we are introducing a feature request queue: https://github.com/skylines-project/skylines/issues?q=label%3Afeature-request+is%3Aclosed+sort%3Areactions-%2B1+. we will close feature requests immediately and label them with "feature-request" so that they will show up in the queue, which is sorted by 👍 reactions. since this issue is also a feature request we have labeled it appropriately and will close it now.
