### ISSUE TITLE
Live Tracking: queued fixes

### ISSUE THREAD

**Issue by ubx** [skylines-project/skylines#412]
In my SkyLines tracking client I've implemented a queue for position-fixes when there is no Internet connection. Fixes are sent when the connection is back again.

A look at the SkyLines server code (server.py) shows that fixes older than 1800 seconds are set to receiving time. For use in SAR Operations it would be nice to have those fixes in a correct order.

**Comment by Turbo87** [comment]
I agree on that. XCSoar 6.8 has such a queue now too, so you are not alone with that problem.

**Comment by Turbo87** [comment]
to cut down on the number of open issues on this project we are introducing a feature request queue: https://github.com/skylines-project/skylines/issues?q=label%3Afeature-request+is%3Aclosed+sort%3Areactions-%2B1+. we will close feature requests immediately and label them with "feature-request" so that they will show up in the queue, which is sorted by 👍 reactions. since this issue is also a feature request we have labeled it appropriately and will close it now.
