### ISSUE TITLE
Seperate Messages and Notifications

### ISSUE THREAD

**Issue by lordfolken** [skylines-project/skylines#413]
Currently Messages/Comments on flights are drowning in my notification feed. Separating comments reps. Messages out from the notification feed would facilitate social interaction. Additionally notification via E-mail for comments would be cool. :-)

**Comment by Turbo87** [comment]
:+1:

**Comment by Turbo87** [comment]
to cut down on the number of open issues on this project we are introducing a feature request queue: https://github.com/skylines-project/skylines/issues?q=label%3Afeature-request+is%3Aclosed+sort%3Areactions-%2B1+. we will close feature requests immediately and label them with "feature-request" so that they will show up in the queue, which is sorted by 👍 reactions. since this issue is also a feature request we have labeled it appropriately and will close it now.
