### ISSUE TITLE
Derive wind from GPS trace

### ISSUE THREAD

**Issue by roeles** [skylines-project/skylines#415]
Please show the wind direction and velocity as derived by Xcsoar. It allows for a more in-depth analysis of flights and could also be used to display (for example) a glide amoeba.

**Comment by Turbo87** [comment]
to cut down on the number of open issues on this project we are introducing a feature request queue: https://github.com/skylines-project/skylines/issues?q=label%3Afeature-request+is%3Aclosed+sort%3Areactions-%2B1+. we will close feature requests immediately and label them with "feature-request" so that they will show up in the queue, which is sorted by 👍 reactions. since this issue is also a feature request we have labeled it appropriately and will close it now.
