### ISSUE TITLE
Delete club

### ISSUE THREAD

**Issue by Harry-R** [skylines-project/skylines#537]
There is no possibility to delete clubs, but sometimes it is necessary. 
For example [here](https://skylines.aero/search?text=sportflug%20niederberg)  a user accidentally created a club multiple times.
Who should be possible to delete a club? The person, who created it?

**Comment by Turbo87** [comment]
> Who should be possible to delete a club? The person, who created it?

since we currently don't have a permissions system for clubs the `owner` is the only one that should be allowed to delete the club. the more interesting cases are:

- what if the owner left the club?
- what if the owner left the club and the club has no members anymore?
- what about the flights assigned to the club?

**Comment by Harry-R** [comment]
Good questions :D 
I think additionally we need a function, which allows the pilot to assign the flight to another club. Should i write an own issue for this?

**Comment by Turbo87** [comment]
to cut down on the number of open issues on this project we are introducing a feature request queue: https://github.com/skylines-project/skylines/issues?q=label%3Afeature-request+is%3Aclosed+sort%3Areactions-%2B1+. we will close feature requests immediately and label them with "feature-request" so that they will show up in the queue, which is sorted by 👍 reactions. since this issue is also a feature request we have labeled it appropriately and will close it now.
