### ISSUE TITLE
updates on conversation about flight

### ISSUE THREAD

**Issue by GliderGeek** [skylines-project/skylines#644]
one of the great things about skylines is that you can comment on someone else's flight

it would be great you get a notification when someone else has posted a reply to your comment / has commented on the same flight

**Comment by Turbo87** [comment]
are you talking about a notification via email?

**Comment by GliderGeek** [comment]
no, i mean the same notification as when someone else comments on one of your own flight
notification inside skylines

**Comment by Turbo87** [comment]
oh, I see what you mean. good idea, yeah!

**Comment by Turbo87** [comment]
to cut down on the number of open issues on this project we are introducing a feature request queue: https://github.com/skylines-project/skylines/issues?q=label%3Afeature-request+is%3Aclosed+sort%3Areactions-%2B1+. we will close feature requests immediately and label them with "feature-request" so that they will show up in the queue, which is sorted by 👍 reactions. since this issue is also a feature request we have labeled it appropriately and will close it now.
