### ISSUE TITLE
Soaringspot Task visualizer

### ISSUE THREAD

**Issue by QuintS** [skylines-project/skylines#661]
[Feature requests]
I was following the Dutch nationals and had a look at the new visualizer on [Soaringspot](http://www.soaringspot.com/en_gb/nk-zweefvliegen-2017/tasks/club-klasse/task-5-on-2017-05-28).  It's quite nifty. It uses some "Mapbox gl" for maps and stuff. A pity it does not refer OSM. But anyway, these are the features SkyLines could learn from.
- The "[ ]" button at the top-right I have been missing on SkyLines for a while
- A simple task viewer, if SkyLines "Competitions" ever takes off
- Really clean design

**Comment by Turbo87** [comment]
@QuintS yeah, I've been looking at the MapBox GL JS viewer for quite some time. It does look quite nice. Unfortunately my free time to work on SkyLines is quite limited at the moment so I haven't had time for any major changes or new features like that... 😞

**Comment by Turbo87** [comment]
@QuintS there is one major disadvantage of MapBox GL JS: while it does support a 3D camera it does not support terrain data and it seems like there are no plans for implementing it so our combination of OpenLayers for 2D stuff and Cesium for 3D seems more fitting for now

**Comment by Turbo87** [comment]
to cut down on the number of open issues on this project we are introducing a feature request queue: https://github.com/skylines-project/skylines/issues?q=label%3Afeature-request+is%3Aclosed+sort%3Areactions-%2B1+. we will close feature requests immediately and label them with "feature-request" so that they will show up in the queue, which is sorted by 👍 reactions. since this issue is also a feature request we have labeled it appropriately and will close it now.
