### ISSUE TITLE
distance flights as second pilot

### ISSUE THREAD

**Issue by GliderGeek** [skylines-project/skylines#664]
Dont know if it's a bug or by design:
the overview of distance flights (as seen below), only takes those flights in which you are the first pilot.
if it's by design then it seems a bit off since the normal 'flights' under your username, also encorporate the ones in which you are the second pilot

<img width="394" alt="screen shot 2017-06-26 at 23 58 15" src="https://user-images.githubusercontent.com/16109193/27562155-7758caec-5acb-11e7-8c1f-6cdeacfa82e8.png">

**Comment by Turbo87** [comment]
that was actually done by design since the second person in a double seater can often be a flight student or an other not that experienced pilot that's not actually flying the majority of the flight. I know there are a lot of exceptions to this, but I think lifting that restriction will make the situation even worse.
