### ISSUE TITLE
Post tracks to Livetrack24

### ISSUE THREAD

**Issue by Paulinhao** [skylines-project/skylines#707]
Suggested enhancement.

There is an Android app called TTLivetrack24 which posts position/tracks live to Livetrack24.com.  This is used extensively by the paraglider community.  However it doesn't use UDP (HTTP?) and is therefore not going to be as good in poor signal areas as Skylines.  I wrote to the TTLivetrack24 developer about this but he could not see the benefit of a 'less reliable' protocol.

I notice that Skylines can receive from Livetrack24 but it would be wonderful if Skylines could be used to post live to livetrack24.com.  

Similarly, why not save tracks in Skylines rather than having to upload them from another source?
Cheers.

**Comment by Turbo87** [comment]
@Paulinhao that is an interesting idea. I'm not using LT24 myself so I'm unlikely to implement this myself, but if someone wants to implement it I can surely review and provide guidance.

> why not save tracks in Skylines rather than having to upload them from another source?

you mean why not use live tracks instead of IGC files? mostly because live tracks are much less reliable due to poor signal in some areas.
