### ISSUE TITLE
Dutch airspace obsolete

### ISSUE THREAD

**Issue by roeles** [skylines-project/skylines#913]
The map around Hilversum shows that airspace is obsolete.
EHP25 changed from a rectangle to a circle.

The new OpenAir airspace file can be downloaded here:
https://www.dropbox.com/s/s3vhiut5ofr609p/EHv18_3.txt?dl=0

**Comment by roeles** [comment]
@Turbo87 Since I have access to the skylines server, I'd be happy to update this myself... can I find instructions somewhere?
Near my home airfield an important change was made, so I'd like to update the map on skylines :-)

**Comment by Turbo87** [comment]
There is a manage.py subcommand to import airspace. iirc it has two modes, you will need to one where you specify the files on the command line instead of importing the airspaces for all countries.

Once that has worked you need to reset the cache of the mapproxy. I'm not sure anymore if there is a command for that too, but I think I saw something like that. 

Good luck :)

**Comment by Turbo87** [comment]
should be updated now

**Comment by roeles** [comment]
Looks good, thanks!
