### ISSUE TITLE
Flight Upload API

### ISSUE THREAD

**Issue by ekurutepe** [skylines-project/skylines#921]
Hello there, thanks for the website and keep up the great work! 

I'm developing an iOS app for glider pilots and I'd love to have the feature to upload IGC files from the app directly to SkyLines.aero. Do you have an upload API? What is a good place for me to start looking?

**Comment by Turbo87** [comment]
@ekurutepe hey, that sounds great. we currently do have an API, but I'm having a hard time promoting it as stable because there are still a few things I would like to change about it.

the current API uses a POST request to https://skylines.aero/api/flights/upload/ to upload new flights. you will have to send a few parameters, an authentication header and the IGC file itself as a `content-type: multipart/form-data` request.

authentication can be either an OAuth token or using "Basic Authorization" (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization) using email address and password of the user.

the supported parameters are `pilotId` and `pilotName`, and iirc the same is supported for `copilot`.
