### ISSUE TITLE
Flight times in local time?

### ISSUE THREAD

**Issue by jthuvili** [skylines-project/skylines#95]
Could the flight times be displayed in local time? IMHO in most cases it would be more informative.

**Comment by pyrog** [comment]
> Could the flight times be displayed in local time?

👍

**Comment by Turbo87** [comment]
to cut down on the number of open issues on this project we are introducing a feature request queue: https://github.com/skylines-project/skylines/issues?q=label%3Afeature-request+is%3Aclosed+sort%3Areactions-%2B1+. we will close feature requests immediately and label them with "feature-request" so that they will show up in the queue, which is sorted by 👍 reactions. since this issue is also a feature request we have labeled it appropriately and will close it now.

**Comment by elgandoz** [comment]
This would be a great addition for all the pilots flying far from UTC, and for the ones who fly in different timezones.
Technically, we could use [Moment.js Timezone library]( https://momentjs.com/timezone/), which would apply the formatted timezone on frontend only.
Timezone should be taken from Take-off/Landing airport and could be displayed on details view and table list.
Sorting would remain based on UTC.
